import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './componentes/navbar'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Exs Jónatas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
